baseURL = "https://expertanalytics.no/"
languageCode = "en-us"
title = "Expert Analytics"
summaryLength = 500
googleAnalytics = "UA-153490291-1"

[params]
copyright = "Â© Expert Analytics AS"
director = "asmund"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

[taxonomies]
  services = "services"
